### ISSUE TITLE
Canary 0.3.2 removes styles from other elements

### ISSUE THREAD

**Issue by michaelarnauts** [jcwillox/lovelace-canary#15]
It seems since version 0.3.2, the styles of other cards are removed. I notice this with the https://github.com/custom-cards/button-card for example.

It seems obvious that this is the cause: https://github.com/jcwillox/lovelace-canary/commit/20f145ed610b76f7c21d8e247aaf3084d76d6df8

**Comment by jcwillox** [comment]
Yeah, this is semi-intended, I now override the `cssText` option, before I was setting the actual properties, but that had issues, for example `margin-right` wouldn't work it needed to be `marginRight` and CSS variables wouldn't work e,g. `--paper-color: red`. So this is definitely a better method, however, it can potentially override the `cssText` styles from other cards, or be overridden by them too.

I'll try appending the styles to `cssText`, instead of overriding them which should fix this issue.

**Comment by jcwillox** [comment]
This should be fixed in [0.3.3](https://github.com/jcwillox/lovelace-canary/releases/tag/0.3.3)

**Comment by michaelarnauts** [comment]
0.3.3 indeed fixed the issue. Thanks!
